---
title: "Sweep Venn"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(VennDiagram)
library(RColorBrewer)
```

Venn diagram of sweep intersections

```{r}
read_si <- function(path,score_threshold){
  sweep_intersections <- read_table2(path,col_names = c("l1","l2","score","overlap"))
  si <- sweep_intersections %>% spread(l2,overlap) %>% 
    filter(score==score_threshold) %>% 
    as.data.frame() %>% 
    column_to_rownames("l1") %>% 
    select(-score) %>% 
    as.matrix()
  si
}

draw_4way_venn <- function(si){
  venn4 <- draw.quad.venn(
    si["fi","fi"],
    si["pi","pi"],
    si["di","di"],
    si["pr","pr"],
    si["fi","pi"],
    si["fi","di"],
    si["fi","pr"],
    si["pi","di"],
    si["pi","pr"],
    si["di","pr"],
    si["12","3"],
    si["12","4"],
    si["13","4"],
    si["23","4"],
    si["123","4"],
    category = c("FI","PI","DI","PR"),
    fill = brewer.pal(4,"Set3"),
    fontface = rep("plain", 15)
    )
    grid.draw(venn4)
}
```

```{r}
si_30 <- read_si("raw_data/SF2/sweep_intersection_table.txt",30)

pdf("figures/SF2_30_Venn.pdf")
draw_4way_venn(si_30)
dev.off()
```

```{r}
si_50 <- read_si("raw_data/SF2/sweep_intersection_table.txt",50)

pdf("figures/SF2_50_Venn.pdf")
draw_4way_venn(si_50)
dev.off()
```
